[app]
address = "127.0.0.1:8080"
run_mode = "release"

[mysql]
dsn = "user:password@tcp(127.0.0.1:3306)/database_name?parseTime=true&loc=Asia%2FShanghai&charset=utf8mb4"
max_idle_conns = 5
max_lifetime = 600
max_open_conns = 10

[log]
level = "debug"
style = "json"